### PR TITLE
feat(opentracing): add support for an opentracing query observer

### PR DESCRIPTION
**Pull request by FrankSpitulski**
Closes https://github.com/gocql/gocql/issues/951

### CODE REVIEW

**Comment by FrankSpitulski** [comment]
the tags match https://github.com/opentracing-contrib/java-cassandra-driver as best as I can

**Comment by nightlyone** [comment]
This could happily live in a different package as the implementation uses only exposed publically exposed interfaces. In fact we use the same interface (and a bit more machinery) to implement the opencensus version of tracing for gocql.

Background: The people behind opentracing and opencensus now work together on a new, unified [open telemetry standard](https://opentelemetry.io/about/) and stated they will obsolete opentracing as well as opencensus when that work is done, I would suggest NOT adding either of opentracing and opencensus to gocql and instead keep the APIs open enough to implement it outside of this package to lower future maintenance efforts.

**Comment by FrankSpitulski** [comment]
Sure, that's how I'm using it now. I just figured you might want it in here since there was an open issue to add it where a contributor asked for someone to help.

**Comment by Zariel** [comment]
I do not want to have this in the main tree, I am happy to have a gocql-contrib repo with this and other monitoring helpers in it.

**Comment by martin-sucha** [comment]
Closing as this won't go to the main gocql/gocql tree/package. @Zariel if you create the gocql-contrib repo, perhaps we could move `HostPoolHostPolicy` there as well (and deprecate in gocql/gocql in v1), as it too just wraps an external dependency.

**Pull request closed without merging**
