### PR TITLE
Update deprecated package

### PR DESCRIPTION
**Pull request by acasajus**
At http://speter.net/ it says that the speter.net/go/exp/math/dec/inf has been replaced by gopkg.in/inf.v0

### CODE REVIEW

**Comment by acasajus** [comment]
Euh... What a nice trace... Any hints?

**Comment by tux21b** [comment]
Seems to be related to your pull request:

    --- FAIL: TestSliceMap-2 (1.53 seconds)
    	cassandra_test.go:706: select: can not unmarshal decimal into *inf.Dec

**Comment by Zariel** [comment]
That import exists in other files, which also need updating other wise the types wont match up

**Comment by Zariel** [comment]
Can you add yourself to the AUTHOR file please, will merge after the build passes now

**Comment by acasajus** [comment]
Last commit is to fix merge conflicts

**Comment by Zariel** [comment]
Thanks, closes #401

**Comment by acasajus** [comment]
Cheers!

**Pull request merged**
