### PR TITLE
query: fixes pagination with query binding

### PR DESCRIPTION
**Pull request by dahankzter**
Paging state was not reset in query::Bind which effectively broke
paging when Bind was used.

Fixes: #1364

### CODE REVIEW

**Comment by dahankzter** [comment]
What do you think @alourie ? This must be pretty common no?

**Comment by alourie** [comment]
@dahankzter yep, sounds about right. Do you think we might reset anything else on `Bind`, it seems as if we're basically running a completely new query at this point.

**Comment by dahankzter** [comment]
We may need others but this one was so clear and isolated that I thought it best to send it first.

**Comment by alourie** [comment]
Fine by me, I'll merge it as obviously fixing an issue. Thanks!

**Pull request merged**
