### PR TITLE
#992: Add ability to collect stats

### PR DESCRIPTION
**Pull request by nyanshak**
WIP, would like to get some feedback and refine the solution + stat names.

### CODE REVIEW

**Comment by Zariel** [comment]
Thanks for starting this, some high level comments about the approach:
* I don't think its a great idea to launch a goroutine for every stat
* We need a real noop stat collector

**Comment by nyanshak** [comment]
Updated the PR with your feedback in mind.

**Comment by nyanshak** [comment]
@Zariel can you give this another look?

**Comment by Zariel** [comment]
Sorry for the delay. Fundamentally I think we need to add some kind of stat exporting to the driver, but I want to be careful to not tie us to specific ways of doing it. Take for example in this case, we can never change any of the metric names because someone might have alerts defined on them. I would rather have a mechanism to export info from the driver and have external code do the monitoring, for example by using #1023

**Pull request closed without merging**
