### PR TITLE
enable the race detector

### PR DESCRIPTION
**Pull request by Zariel**

### CODE REVIEW

**Comment by 0x6e6562** [comment]
This needs re-merging.

**Comment by Zariel** [comment]
dont know what caused this to fail

**Comment by Zariel** [comment]
With having the cover profile running it makes it pretty much impossible to figure out what is going wrong in that test to cause it to fail.

**Comment by 0x6e6562** [comment]
Is it worth splitting this into two test runs (for coverage, one for races) for debugging purposes (or just disabling coverage for now)?

With regards to coverage, I think on average we are higher than 55% right now, but that's a separate issue: #278

**Comment by Zariel** [comment]
created #368 to discuss this

**Pull request closed without merging**
