### PR TITLE
CASSGO-28 ignore error retry type

### LINKED ISSUE #1808: CASSGO-28 Retry type Ignore is not different from Rethrow (error is still returned)
### What version of Cassandra are you using?
Scylla Enterprise 2024.1.8 or scylla 5.1 

### What version of Gocql are you using?
github.com/gocql/gocql v1.6.0

### What version of Go are you using?
go 1.21.11

### What did you do?
used RetryType Ignore (https://pkg.go.dev/github.com/gocql/gocql#RetryType) on write query 

### What did you expect to see?
I expected that query.Exec() would not return error  

### What did you see instead?
the error is returned.

---

Maybe the documentation is not clear on how Ignore and Rethrow are different? 

I thought Ignore would make it so that Exec does not return error ? Maybe this would be strange on read ops but it can be used on writes (in Downgrading CL retry policy for example ). But they both return error and I don't see any difference between those retry types 

Is there any difference in Rethrow and Ignore retry types  ?

### PR DESCRIPTION
**Pull request by Rikkuru**
Closes https://github.com/apache/cassandra-gocql-driver/issues/1808

### CODE REVIEW

**Comment by joao-r-reis** [comment]
Can you add a test to ensure that the issue is actually fixed? And to prevent regressions.

**Comment by Rikkuru** [comment]
> ### This branch has no conflicts with the base branch when rebasing

Hello! OK I will try to get to it on this weekend

**Comment by Rikkuru** [comment]
> Can you add a test to ensure that the issue is actually fixed? And to prevent regressions.

Added a test. Wanted to let observer know that error was ignored but observer is called before retry policy is checked.

there is one more problem - error will not be ignored if we have no more attempts. Added a fix&test for this too

**Review by joao-r-reis — APPROVED** [review]
Looks good. +1 assuming CI passes.

Please format your commit message following the rules stated in [CONTRIBUTING.md](https://github.com/apache/cassandra-gocql-driver/blob/trunk/CONTRIBUTING.md#commit-message) and add this JIRA to the `CHANGELOG.md` in the `Fixed` section of `Unreleased`, thanks!

If you can't squash and rewrite the commit message the committer will do it for you when the PR is merged.

We need another committer +1 to merge this.

**Comment by Rikkuru** [comment]
> We need another committer +1 to merge this.

You mean anyone who've made a commit or apache employee ?

**Comment by joao-r-reis** [comment]
> > We need another committer +1 to merge this.
> 
> You mean anyone who've made a commit or apache employee ?

Committers are people who have write access to the codebase, a PR needs two +1s from committers to get merged ideally and I'm a committer so we need one more.

**Comment by Jacko161** [comment]
LGTM - just needs conflicts to be resolved.

**Review by Jacko161 — APPROVED** [review]

**Comment by Rikkuru** [comment]
> just needs conflicts to be resolved

Resolved conflicts with rebase

**Comment by joao-r-reis** [comment]
Please also add Jackson as a reviewer to the commit message and I'll merge this afterwards

**Pull request merged**
