### PR TITLE
Introduce an integration test for authentication

### PR DESCRIPTION
**Pull request by 0x6e6562**
This patch squashes #316.

### CODE REVIEW

**Comment by Zariel** [comment]
I would remove the cqlsh checks, if gocql doesnt work then the python driver shouldnt

**Comment by 0x6e6562** [comment]
Yes, you're right - the cqlsh check was only introduced to debug the test run and shed more light on the situation.

**Comment by 0x6e6562** [comment]
@Zariel It looks like this variant might work.

**Comment by Zariel** [comment]
The struggle has a happy ending :) good job!

**Pull request merged**
