### PR TITLE
Update new contribution agreement from Ghais Issa

### PR DESCRIPTION
**Pull request by michaelsembwever**
patch by Mick Semb Wever; reviewed by XXX for CASSANDRA-19723

### CODE REVIEW

**Review by martin-sucha — APPROVED** [review]
Related comment: https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2189623544

**Comment by michaelsembwever** [comment]
> Related comment: https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2189623544

Oh, thanks for point that out, now I see/remember there's others too that have since given their approval.
Commit updated…

**Comment by martin-sucha** [comment]
It is not clear to me whether Árni Dagur and Tushar Das should have an asterisk, since the comments https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2196472803 and https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2245661503 both say that they haven't signed the CLA and the top of the NOTICE file says

```
Where The Gocql Authors for copyright purposes are below. Those marked with
asterisk have agreed to donate (copyright assign) their contributions to the
Apache Software Foundation, signing CLAs when appropriate.
```

I haven't looked into whether signing the CLA is necessary in this case or not.

**Comment by michaelsembwever** [comment]
> It is not clear to me whether Árni Dagur and Tushar Das should have an asterisk, since the comments https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2196472803 and https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2245661503 both say that they haven't signed the CLA and the top of the NOTICE file says 

They both expressed (at least I understood) that their work could be used and that signing the CLA didn't seem necessary.  That's enough for us, as we're still keeping the copyright in place for work pre-donation.

**Review by martin-sucha — APPROVED** [review]
Thanks! That solves my concerns.

**Pull request merged**
