### PR TITLE
Fix murmur3 library for murmur3partitioner

### PR DESCRIPTION
**Pull request by zviadm**
* Cassandra murmur3 needs to use int64s
* Removed use of unsafe package, because perf benefits are questionable,
  and creates unnecessary compatibility issues.

### CODE REVIEW

**Comment by zviadm** [comment]
Fixes #1033

**Comment by Zariel** [comment]
Thanks have fixed via #1035

**Comment by zviadm** [comment]
Test case might still be helpful, just to make sure you are testing all 16 versions of the switch statement, and also to make sure you are testing with inputs that have bytes larger than 128

**Comment by Zariel** [comment]
Agreed, would you like to submit he test cases by themselves from this?

**Pull request closed without merging**
