### PR TITLE
Correctly handle null value for varint type

### PR DESCRIPTION
**Pull request by vecmezoni**
Got panic while fetching null value for varint type:
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range
github.com/gocql/gocql.unmarshalVarint(0x13b4630, 0xc820075860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/vecmezoni/go/src/github.com/gocql/gocql/marshal.go:435 +0x40c
github.com/gocql/gocql.Unmarshal(0x13b4630, 0xc820075860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/vecmezoni/go/src/github.com/gocql/gocql/marshal.go:127 +0x7ae
```

### CODE REVIEW

**Comment by vecmezoni** [comment]
Cassandra 2.2.4 with auth fails on master.
Cassandra 2.2.5 test failed with:
```
 The command "go get golang.org/x/tools/cmd/vet" failed and exited with 1 during .
```

**Comment by Zariel** [comment]
Thanks, the test failures look odd but unrelated. Can you add yourself to the AUTHORS file if not already and I will merge.

**Comment by vecmezoni** [comment]
Done :+1:

**Comment by Zariel** [comment]
if you rebase and push it should work in travis now

**Comment by Zariel** [comment]
thanks very much

**Pull request merged**
