### PR TITLE
Add func (*Query)MapScan(map[string]interface{})

### PR DESCRIPTION
**Pull request by matope**
Iter.MapScan(map[string]interface{}) Method is an useful interface to imprement data bindings.
It would be nice if *Query also has this method.

Could you review this PR?

### CODE REVIEW

**Comment by phillipCouto** [comment]
I +1 the addition of the MapScan to the Query type. As for the testing it looks like you reduced boiler plate code for the test and used an existing function. 

To me this PR looks good.

**Comment by 0x6e6562** [comment]
OK, I've reviewed the outright version for `cassandra_test.go` and it is now clear that the changes to this file a good simplification and that the test coverage has indeed not been reduced.

**Comment by 0x6e6562** [comment]
Since I was indifferent about the change and @phillipCouto thinks it's a good idea, I think the best thing to do is to get on and merge this.

@matope Thank you for your contribution and apologies for the time taken to merge this pull request.

**Comment by matope** [comment]
Thanks a lot!

**Pull request merged**
