### PR TITLE
conn: replace streams chan with an ID generator

### PR DESCRIPTION
**Pull request by Zariel**
Replace the bounched chan uniq with a stream ID generator based
very closely on the StreamIDGenerator in the java-driver.

Updates #446

### CODE REVIEW

**Comment by Zariel** [comment]
@nemothekid this should further reduce the size overhead of head connection.

**Comment by Zariel** [comment]
Though this removes the ability to configure number of streams to use, but we wont preallocate them now.

**Comment by nemothekid** [comment]
AFAICT, On one hand this does bring us inline with the "official" implementation, on the other hand, we lose the ability to specify the number of streams (might not be a bad thing, I don't think anyone changed the value, and it might be a useless option) and we lose the ability for connections to wait for an available stream.

What happens when we get `ErrNoStreams`, do we just Retry according to the RetryPolicy or tell the application to deal with it?

**Comment by Zariel** [comment]
I think the round robin conn policy doesn't check for available streams on a conn, will fix that in another PR.

**Pull request merged**
