### PR TITLE
Fix list unmarshaling

### PR DESCRIPTION
**Pull request by c0va23**
This is an updated and an cleared version of PR #302. This version can be merged without #287.

### CODE REVIEW

**Comment by Zariel** [comment]
Is there an example test case which the current code fails for? I would say this looks good to me but could do with a bit of convincing as to what this is solving. Also is your email in the `AUTHORS.md` file?

**Comment by c0va23** [comment]
Example described into #302.
I have already indicated in the list of authors.

**Comment by Zariel** [comment]
Thanks for the contribution!

**Comment by c0va23** [comment]
Thank you for your promptness.

**Pull request merged**
