### PR TITLE
Fix memory leakage  when running bulk insertions

### PR DESCRIPTION
**Pull request by criloz**
it was using 950 MB after running by  5 minutes

### CODE REVIEW

**Comment by phillipCouto** [comment]
Can we see an example of the batch statements you are executing?

**Comment by criloz** [comment]
BATCH with 2000 insertions. now all its running ok, the app barely go over 18 mb

**Comment by phillipCouto** [comment]
Yes but you are introducing an inefficiency by purging the LRU which defeats the purpose of it to start with. Can you paste an example of one of your INSERT statements from your program. Preferably the Go code that adding the insert statement to the batch would be great.

**Comment by criloz** [comment]
```go
css.buffer[worker] = "BEGIN BATCH\n" + css.buffer[worker] + "\nAPPLY BATCH;"
q := css.session.Query(css.buffer[worker])
```

is there a way to disable this cached?

**Comment by phillipCouto** [comment]
What version of Cassandra are you using?

**Comment by criloz** [comment]
Ahh  sorry I just notice that there is a Batch type struct, sorry my error. I will close the pull request.

**Comment by phillipCouto** [comment]
no problem. Also try to use parameters in your statements. Like:
```
batch.Query("INSERT INTO Table (Col1,Col2,Col3) VALUES (?,?,?)",1,2,3)
```

This will only cache one copy of your query and keep your memory usage to a minimum and improve write performance in Cassandra.

**Comment by criloz** [comment]
Thanks!!

**Comment by 0x6e6562** [comment]
@criloz Does this pull request need to remain open?

**Comment by criloz** [comment]
@0x6e6562  tried, but the github ui don't let me  close it.

**Pull request closed without merging**
