### PR TITLE
Reuse a timer to prevent excessive allocations

### PR DESCRIPTION
**Pull request by jbardin**
- Every call to Conn.exec creates a new timer with the call to
  time.After. These are alive in memory for the duration of the timer,
  and can add a lot of overhead on a busy connection with a long
  timeout.
- Add a timer to the Conn struct that can be reused on every call to
  exec.

### CODE REVIEW

**Comment by jbardin** [comment]
I saw this issue here: http://stackoverflow.com/questions/35512541/timer-overhead-causing-memory-overflow

**Comment by Zariel** [comment]
Thanks for looking at this, unfortunately this will apply a timeout globally on a connection wheras the previous implementation will set a timeout per query. Queries are multiplexed onto connections so there can be many connections on the same connection. A fix could be to move the timer onto `callReq` which are recycled in a `sync.Pool`

**Comment by jbardin** [comment]
Sorry, should have mentioned I'm not familiar with this code base at all, and might have missed something. Feel free to close this and push a better change in another PR if you want. I might be a few days before I have some time to look at it again.

**Comment by Zariel** [comment]
Thanks for the patch and pointing to the StackOverflow issue, I've filed #661

**Pull request closed without merging**
