### PR TITLE
Allow to use protocol V5

### PR DESCRIPTION
**Pull request by beltran**

### CODE REVIEW

**Comment by Zariel** [comment]
This doesn't cover the full change for Proto v5 since v4

- [x] Beta protocol flag for v5 native protocol is added (Section 2.2)
- [ ] <numfailures> in Read_failure and Write_failure error message bodies (Section 9)
    has been replaced with <reasonmap>. The <reasonmap> maps node IP addresses to
    a failure reason code which indicates why the request failed on that node.
- [x] Enlarged flag's bitmaps for QUERY, EXECUTE and BATCH messages from [byte] to [int]
    (Sections 4.1.4, 4.1.6 and 4.1.7).
- [ ] Add the duration data type
- [ ] Added keyspace field in QUERY, PREPARE, and BATCH messages (Sections 4.1.4, 4.1.5, and 4.1.7).
- [ ] Added [int] flags field in PREPARE message (Section 4.1.5).

**Comment by beltran** [comment]
Can you review @Zariel

**Comment by Zariel** [comment]
Thanks very much!

**Comment by beltran** [comment]
My pleasure

**Pull request merged**
