### PR TITLE
Return routing key for one the elements in the IN clause if they are …

### PR DESCRIPTION
**Pull request by beltran**
…part of the key

See https://github.com/gocql/gocql/issues/1177

### CODE REVIEW

**Comment by Zariel** [comment]
please see https://github.com/gocql/gocql/issues/1177#issuecomment-419672095

**Comment by Zariel** [comment]
Also this does not have tests and I doubt it would work, fundamentally this is not a good idea.

**Comment by beltran** [comment]
Why wouldn't it work @Zariel ?

**Comment by Zariel** [comment]
`SELECT * FROM table WHERE key IN (1, 2, 3, 4, 5)`

**Comment by beltran** [comment]
I don't think I understand @Zariel

**Pull request closed without merging**
