### PR TITLE
Support for Go 1.4

### PR DESCRIPTION
**Pull request by 0x6e6562**
This patch investigates whether Go 1.4 can be supported.

### CODE REVIEW

**Comment by Zariel** [comment]
Should we also remove 1.2 as an official supported version to maintain the latest 2 supported major versions?

**Comment by 0x6e6562** [comment]
@Zariel Good question - this patch started as an investigation as to whether 1.4 can be supported, but ultimately I think you've got a point - we can't just increase the maintenance scope ad infinitum. Maybe we should come to some of consensus before ploughing ahead with this change. @phillipCouto ?

**Comment by Zariel** [comment]
I think when we added 1.3 we removed 1.1 and agreed to support the last 2, let me see if I can find it.

**Comment by Zariel** [comment]
Also given that supporting 1.2 as a minimum blocks issues such as #295

**Comment by phillipCouto** [comment]
I think supporting the latest version and one previous is a good model. We should execute the sunsetting of 1.2 similar to 1.1. Create a tag signaling the latest version of 1.2 support and then discontinue it.

**Comment by 0x6e6562** [comment]
OK, agreed - I'll add some notes to the README about the sunset model.

**Comment by 0x6e6562** [comment]
@Zariel I think there is some confusion here - I don't think this pull request was quite ready to go. I had left it alone for a couple of weeks because I have been so snowed under with other tasks. I'm not sure that all of the components in the Travis matrix pass (I've just kicked a couple of failing ones off again). Also we have support for 1.2 still, that was supposed to get sunset. And this change in the maintenance model wasn't documented yet.

**Comment by 0x6e6562** [comment]
I've kicked the build off again - 594.5 seems to have issues getting past TestRingDiscovery though.

**Comment by 0x6e6562** [comment]
OK, so the build has finally passed, so the jump to 1.4 is OK. Once I get the head space, I'll remove 1.2 and document the sunset model accordingly.

**Pull request merged**
