### PR TITLE
query: dont leak contexts with cancels

### LINKED ISSUE #1224: Memory leak in context.WithCancel
### What version of Cassandra are you using?
2.2.12

### What version of Gocql are you using?
https://github.com/gocql/gocql/commit/22229812a83e

Commit https://github.com/gocql/gocql/commit/08a3a27c42ccc63167b9d470472b85983e17e0e2 introduced memory leak.
image
Rollback to previous version fixes issue.

From https://golang.org/pkg/context/#WithCancel:
_Canceling this context releases resources associated with it, so code should call cancel as soon as the operations running in this Context complete._
So `cancelQuery` should be called after query execution?

### PR DESCRIPTION
**Pull request by Zariel**
Use context to propagate failure of queries when running query
speculation and remove the ability to explicitly cancel queries, instead
relying on the caller to cancel the context provided.

fixes #1224

### CODE REVIEW

**Comment by Zariel** [comment]
cc @alourie

**Comment by Zariel** [comment]
failure is due to context canceled I think, doesnt replicate locally though.

**Comment by beltran** [comment]
I can repro locally @Zariel, gets fixed if I add `results <- queryResponse{err: ctx.Err()}` before [this return](https://github.com/Zariel/gocql/blob/aba4194327a07baa1d682f05aa5cddbd6c00903d/query_executor.go#L125).

**Comment by Zariel** [comment]
closing in favour of #1228 which is more robust

**Pull request closed without merging**
